#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "material"
    #colorscheme_bg = "color201"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # install nerd fonts
    buffer_index_type = 4
    filetree_direction = "left"

    # statusline
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    buffer_index_type = 0
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]

# Enable autocomplete layer
[[layers]]
 name = 'autocomplete'
 auto_completion_return_key_behavior = "complete"
 auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
 name = "lang#go"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "core#statusline"

[[layers]]
 name = "fzf"

[[layers]]
  name = "leaderf"

[[layers]]
  name = "colorscheme"
  random_theme = true

[[layers]]
  name = "tmux"

[[layers]]
  name = "git"
